### ISSUE TITLE
Beginner Questions

### ISSUE THREAD

**Issue by stdavis** [github/training-kit#354]
I'm teaching an introductory GitHub workshop at a conference next month and was excited to find this repo. Thanks for sharing it!

I'm struggling with how to get started. I see that you have slides hosted at: https://training.github.com/kit/ but they don't seem like an ideal solution. Do you really use the scroll bar to advance slides? I can see docs in your repo about full screen slides and speaker notes but can't figure out how to use those features.

I also tried running `./_buildscripts/cibuild` but was unsuccessful...
```
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
hostname: sttla-lb1-12.utah.utad.state.ut.us
pwd: /Users/stdavis/Documents/Projects/github-ugic-workshop
git version 2.6.4
==> Installing gem dependencies…
==> Cloning into submodules
rake aborted!
LoadError: Could not open library 'c': dlopen(c, 5): image not found.
Could not open library 'libc.dylib': dlopen(libc.dylib, 5): image not found
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/ffi-1.9.6/lib/ffi/library.rb:133:in `block in ffi_lib'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/ffi-1.9.6/lib/ffi/library.rb:100:in `map'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/ffi-1.9.6/lib/ffi/library.rb:100:in `ffi_lib'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/ethon-0.7.1/lib/ethon/libc.rb:8:in `<module:Libc>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/ethon-0.7.1/lib/ethon/libc.rb:6:in `<module:Ethon>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/ethon-0.7.1/lib/ethon/libc.rb:1:in `<top (required)>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/ethon-0.7.1/lib/ethon.rb:10:in `require'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/ethon-0.7.1/lib/ethon.rb:10:in `<top (required)>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/typhoeus-0.6.9/lib/typhoeus.rb:2:in `require'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/typhoeus-0.6.9/lib/typhoeus.rb:2:in `<top (required)>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer/check.rb:6:in `require'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer/check.rb:6:in `<top (required)>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer/checks.rb:11:in `require'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer/checks.rb:11:in `block in <class:Checks>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer/checks.rb:11:in `each'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer/checks.rb:11:in `<class:Checks>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer/checks.rb:3:in `<class:Proofer>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer/checks.rb:2:in `<module:HTML>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer/checks.rb:1:in `<top (required)>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer.rb:13:in `require'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer.rb:13:in `block in <top (required)>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer.rb:13:in `each'
/Users/stdavis/Documents/Projects/github-ugic-workshop/vendor/gems/ruby/2.0.0/gems/html-proofer-1.4.0/lib/html/proofer.rb:13:in `<top (required)>'
/Users/stdavis/Documents/Projects/github-ugic-workshop/Rakefile:1:in `require'
/Users/stdavis/Documents/Projects/github-ugic-workshop/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
```

Thanks, in advance, for helping out a ruby-newbie.

**Comment by crichID** [comment]
@stdavis thank you for your note! Our materials are in a transitional state right now and we are working to update this site. In the meantime, can we send you a copy of our newer materials in their current state? Please drop us a note at services@github.com and we will send you the updated deck and manuals.

**Comment by stdavis** [comment]
Thanks, I sent you an email.

**Comment by stdavis** [comment]
Hey @crichID: I sent an email on 4/9 but never heard anything. Did you get it? My email is stdavis@utah.gov.
